quiz_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/mbi/admin/", admin.site.urls),
    path("accounts/", include("users.urls")),
    path("", include("test_app.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]

test_app/urls.py
from django.urls import path
from .views import (
    TestGroupListView,
    TestGroupCreateView,
    TestCreateView,
    Testing,
    TestGroupDetailView,
)

app_name = "testapp"

urlpatterns = [
    path("", TestGroupListView.as_view(), name="testgroup_list"),
    path("new/testgroup/", TestGroupCreateView.as_view(), name="testgroup_new"),
    path("new/test/", TestCreateView.as_view(), name="test_new"),
    path("testgroup/<int:pk>/", TestGroupDetailView.as_view(), name="testgroup_detail"),
    path("testing/<int:pk>/", Testing.as_view(), name="testing"),
]

users/urls.py
from django.urls import path
from .views import Login, Register, Logout, Profile, EditUser, UsersListView

app_name = "users"

urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("register/", Register.as_view(), name="register"),
    path("logout/", Logout.as_view(), name="logout"),
    path("edit/", EditUser.as_view(), name="edit"),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("<str:username>/", Profile.as_view(), name="profile"),
]

test_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from ckeditor_uploader.fields import RichTextUploadingField


class TestGroup(models.Model):
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='test_group')
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Test(models.Model):
    question = RichTextUploadingField()
    option1 = RichTextUploadingField()
    option2 = RichTextUploadingField()
    option3 = RichTextUploadingField()
    option4 = RichTextUploadingField()
    answer = models.IntegerField(default=1, validators=(MinValueValidator(1), MaxValueValidator(4)))
    test_group = models.ForeignKey(TestGroup, on_delete=models.CASCADE, related_name='test')

    def __str__(self):
        return self.question

users/models.py
from django.db import models

# Create your models here.

test_app/forms.py
from django.forms import ModelForm
from .models import Test, TestGroup


class TestCreateForm(ModelForm):
    class Meta:
        model = Test
        fields = "__all__"

    def __init__(self,user=None,**kwargs):
        super(TestCreateForm, self).__init__(**kwargs)
        if user:
            self.fields['test_group'].queryset = TestGroup.objects.filter(owner__username=user.username).all()

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255)
    password = forms.CharField(max_length=255, widget=forms.PasswordInput)

test_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.db.models import Count
from .models import TestGroup, Test
from .forms import TestCreateForm
from random import shuffle


class TestGroupListView(ListView):
    model = TestGroup
    template_name = "testgroup_list.html"
    context_object_name = "test_groups"
    ordering = ["-created_at"]
    queryset = TestGroup.objects.annotate(tests_count=Count('test'))


class TestGroupCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("users:login")
    model = TestGroup
    template_name = "testgroup_create.html"
    fields = ["name"]

    def form_valid(self, form):
        testgroup = form.save(commit=False)
        testgroup.owner = self.request.user
        testgroup.save()
        return super().form_valid(testgroup)

    def get_success_url(self):
        return reverse("testapp:testgroup_list")


class TestGroupDetailView(View):
    def get(self, r, pk):
        return render(r, "testgroup_detail.html", {"pk": pk})


class TestCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("users:login")
    model = Test

    def get(self, r):
        form = TestCreateForm(user=r.user)
        return render(r, "test_create.html", {"form": form})

    def post(self, r):
        form = TestCreateForm(data=r.POST)

        if form.is_valid():
            form.save()
            return redirect("testapp:testgroup_list")


tests_list = list()


class Testing(View):
    def post(self, r, pk):
        global tests_list
        test_count = r.POST.get("test_count")

        if test_count:
            arr = list(Test.objects.filter(test_group_id=pk).all())
            shuffle(arr)
            tests = arr[: int(test_count)]
            tests_list = tests
            test_group = TestGroup.objects.get(pk=pk)
            return render(r, "testing.html", {"tests": tests, "test_group": test_group})
        else:
            cnt = 0
            tests = list()
            for t in tests_list:
                user_ans = r.POST.get(str(t.pk))
                if user_ans == None:
                    tests.append({"test_data": t, "user_ans": 0})
                else:
                    tests.append({"test_data": t, "user_ans": int(user_ans)})

                if str(t.answer) == str(r.POST.get(str(t.pk))):
                    cnt += 1
            context = {
                "test_group": TestGroup.objects.get(pk=pk),
                "correct": cnt,
                "all": len(tests_list),
                "tests": tests,
            }
            return render(r, "results.html", context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import CreateView, DetailView, View, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout, login
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.db.models import Count
from .forms import UserRegistrationForm, EditUserForm, LoginForm
from test_app.models import TestGroup


class Login(View):
    def get(self, r):
        form = LoginForm()
        return render(r, "login.html", {"form": form})

    def post(self, r):
        form = AuthenticationForm(data=r.POST)
        if form.is_valid():
            login(r, form.get_user())
            return redirect("testapp:testgroup_list")
        else:
            return render(r, "login.html", {"form": form})


class Register(CreateView):
    def get(self, r):
        form = UserRegistrationForm()
        return render(r, "register.html", {"form": form})

    def post(self, r, *args, **kwargs):
        form = UserRegistrationForm(data=r.POST)
        if form.is_valid():
            form.save()
            return redirect("users:login")
        return render(r, "register.html", {"form": form})


class Logout(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy("users:login")

    def get(self, r):
        logout(request=r)
        return redirect("testapp:testgroup_list")


class Profile(View):
    def get(self, r, username):
        print(username)
        user = User.objects.get(username=username)
        test_groups = list(
            TestGroup.objects.filter(owner__username=username)
            .order_by("-created_at")
            .annotate(tests_count=Count('test'))
        )
        return render(r, "profile.html", {"user": user, "test_groups": test_groups})


class EditUser(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy("users:login")

    def get(self, r):
        form = EditUserForm(instance=r.user)
        return render(r, "edit_user.html", {"form": form})

    def post(self, r, *args, **kwargs):
        form = EditUserForm(instance=r.user, data=r.POST)
        if form.is_valid():
            form.save()
            return redirect("users:profile", username=r.user.username)

    def get_success_url(self):
        return reverse("users:profile", kwargs={"username": r.user.username})


class UsersListView(ListView):
    model = User
    template_name = 'users_list.html'
    ordering = ['first_name', 'last_name']
    context_object_name = 'users'
    queryset = User.objects.annotate(testgroup_count=Count('test_group'))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{#    <meta http-equiv="X-UA-Compatible" content="IE=edge">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<header>
    <div class="center">
        <h2><a href="{% url 'testapp:testgroup_list' %}">Quiz Test</a></h2>
        <div class="header__right">
            {% if request.user.is_authenticated %}
                <a href="{% url 'testapp:test_new' %}">Yangi test</a>
                <a href="{% url 'testapp:testgroup_new' %}">Yangi test guruhi</a>
                <a href="{% url 'users:profile' request.user.username %}">Profil</a>
                <a href="{% url 'users:logout' %}">Chiqish</a>
            {% else %}
                <a href="{% url 'users:users_list' %}">Foydalanuvchilar</a>
                <a href="{% url 'users:login' %}">Kirish</a>
                <a href="{% url 'users:register' %}">Hisob yaratish</a>
            {% endif %}
        </div>
    </div>
</header>
<div class="content-container">
    {% block content %}
    {% endblock %}
</div>
</body>
<script type="text/javascript" id="MathJax-script" async
        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.0/es5/latest?tex-mml-chtml.js">
</script>
{% block script %} {% endblock %}
</html>

templates/edit_user.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Foydalanuvchi ma'lumotlarini tahrirlash
{% endblock %}

{% block content %}
    <form method="POST" novalidate class="form-box">
        {% csrf_token %}
        <h2> Ma'lumotlarni tahrirlash </h2>
        {% for field in form %}
            <div class="input-box">
                {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                            <li style="list-style: none;
                                       color:white;
                                       padding: 5px 10px;
                                       background-color: #db5757;
                                       border-radius: 4px;
                            ">
                                {{ error }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="btn"> Saqlash </button>
    </form>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Login {% endblock %}

{% block content %}
    <form method="post" class="form-box">
        <h2>Tizimga kirish</h2>
        {% csrf_token %}
        <div class="input-box">
            <label for="id_username" class="form-label requiredField"> Foydalanuvchi nomi: </label>
            <input type="text" name="username" required id="id_username">
        </div>
        <div class="input-box">
            <label for="id_password" class="form-label requiredField"> Parol: </label>
            <input type="password" name="password" required id="id_password">
        </div>
        {% if form.errors %}
            <div class="red-back opt-box__ans">Foydalanuvchi nomi yoki parol xato </div>
        {% endif %}
        <button type="submit" class="btn">Login</button>
    </form>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% block title %}
    Profil
{% endblock %}

{% block content %}
    <div class="header__right a_link">
        {% if request.user.is_authenticated and request.user.username == user.username %}
            <a href="{% url 'users:edit' %}">Profilni tahrirlash</a>
        {% endif %}
        <a href="{% url 'users:users_list' %}">Foydalanuvchilar</a>
    </div>
    <div class="clean"></div>
    <div class="form-box">
        <h2>{{ user.first_name }} {{ user.last_name }} tomonidan yaratilgan testlar ro'yxati</h2>
        {% for test_group in test_groups %}
            <div class="a_link list-element">
                <a href="{% url 'testapp:testgroup_detail' test_group.pk %}"> {{ test_group.name }} </a>
                <span class="list-element__span">Testlar soni: {{ test_group.tests_count }} </span>
                <span>|</span>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Ro'yxatdan o'tish {% endblock %}

{% block content %}
    <form method="POST" novalidate class="form-box">
        {% csrf_token %}
        <h2>Ro'yxatdan o'tish </h2>

        {% for field in form %}
            <div class="input-box">
                {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                            <li style="list-style: none;
                                       color:white;
                                       padding: 5px 10px;
                                       background-color: #db5757;
                                       border-radius: 4px;
                            ">
                                {{ error }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {{ field.label_tag }} {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="btn"> Jo'natish </button>
    </form>
{% endblock %}

templates/results.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Natijalar
{% endblock %}

{% block content %}
    <div class="form-box">
        <h2>{{ test_group.name }} testi uchun natijalaringiz</h2>
        <h4>To'g'ri javoblar soni: {{ correct }}</h4>
        <h4>Jami testlar soni: {{ all }}</h4>

        {% for test in tests %}
            <div class="test-box">
                <div class="test-box__q {% if test.user_ans == 0 %} red-back {% endif %}">{{ forloop.counter }}. {{ test.test_data.question | safe }}</div>
                <div class="opt-box__ans {% if test.test_data.answer == 1 %} green-back {% elif test.user_ans == 1 %} red-back {% endif %} ">
                    &bullet;{{ test.test_data.option1 | safe }}
                </div>

                <div class="opt-box__ans {% if test.test_data.answer == 2 %} green-back {% elif test.user_ans == 2 %} red-back {% endif %} ">
                    &bullet;{{ test.test_data.option2 | safe }}
                </div>

                <div class="opt-box__ans {% if test.test_data.answer == 3 %} green-back {% elif test.user_ans == 3 %} red-back {% endif %} ">
                    &bullet;{{ test.test_data.option3 | safe }}
                </div>

                <div class="opt-box__ans {% if test.test_data.answer == 4 %} green-back {% elif test.user_ans == 4 %} red-back {% endif %} ">
                    &bullet;{{ test.test_data.option4 | safe }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/test_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Test yaratish {% endblock %}

{% block content %}

    <form method="post" class="form-box">
        <h2>Yangi test yaratish</h2>
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}
        <button type="submit" class="btn">Saqlash</button>
    </form>
{% endblock %}

templates/testgroup_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Testlar guruhini yaratish {% endblock %}

{% block content %}
    <form method="post" class="form-box">
        <h2>Yangi testlar guruhi uchun nom kiriting.</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Saqlash</button>
    </form>
{% endblock %}

templates/testgroup_detail.html
{% extends 'base.html' %}
{% block title %}
    Testni boshlash
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'testapp:testing' pk %}" class="form-box">
        {% csrf_token %}
        <div class="input-box">
            <label for="test_count">Testlar sonini tanlang:</label>
            <input type="number" value="5" name="test_count" id="test_count" min="1" max="50"/>
        </div>
        <button type="submit" class="btn">Boshlash</button>
    </form>
{% endblock %}

templates/testgroup_list.html
{% extends 'base.html' %}
{% block title %} Testlar ro'yxati {% endblock %}

{% block content %}
    <div class="form-box">
        <h2>Mavjud testlar ro'yxati</h2>
        {% for test_group in test_groups %}
            <div class="a_link list-element">
                <a href="{% url 'testapp:testgroup_detail' test_group.pk %}"> {{ test_group.name }} </a>
                <span class="list-element__span">Testlar soni: {{ test_group.tests_count }} </span>
                <span>|</span>
                <span class="list-element__span">
                    Muallif:
                    <a href="{% url 'users:profile' test_group.owner.username %}">{{ test_group.owner.username }}</a>
                </span>
                <span>|</span>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/testing.html
{% extends 'base.html' %}
{% block title %}
    {{ test_group.name }}
{% endblock %}

{% block content %}
    <form method="post" class="form-box">
        <h2>{{ test_group.name }}</h2>
        {% csrf_token %}
        {% for test in tests %}
            <div class="test-box">
                <div class="test-box__q">{{ forloop.counter }}. {{ test.question | safe }}</div>

                <div class="opt-box">
                    <input type="radio" id="opt1{{test.pk}}" name="{{ test.pk }}" value="1">
                    <label for="opt1{{test.pk}}">{{ test.option1 | safe }}</label>
                </div>

                <div class="opt-box">
                    <input type="radio" id="opt2{{test.pk}}" name="{{ test.pk }}" value="2">
                    <label for="opt2{{test.pk}}">{{ test.option2 | safe }}</label>
                </div>

                <div class="opt-box">
                    <input type="radio" id="opt3{{test.pk}}" name="{{ test.pk }}" value="3">
                    <label for="opt3{{test.pk}}">{{ test.option3 | safe }}</label>
                </div>

                <div class="opt-box">
                    <input type="radio" id="opt4{{test.pk}}" name="{{ test.pk }}" value="4">
                    <label for="opt4{{test.pk}}">{{ test.option4 | safe }}</label>
                </div>
            </div>
        {% endfor %}
        <button type="submit" class="btn"> Yakunlash </button>
    </form>
{% endblock %}

templates/users_list.html
{% extends 'base.html' %}
{% block title %}
    Foydalanuvchilar
{% endblock %}

{% block content %}
    <div class="form-box">
        <h2>Foydalanuvchilar:</h2>
        {% for user in users %}
            <div class="a_link list-element">
                <a href="{% url 'users:profile' user.username %}"> {{ user.first_name }} {{ user.last_name }} </a>
                <span class="list-element__span">Testlari soni: {{ user.testgroup_count }}</span>
                <span>|</span>
            </div>
        {% endfor %}
    </div>
{% endblock %}